apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: bvault-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 24h
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /lab/compute/postgres_password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /lab/compute/postgres_user
    - secretKey: POSTGRES_DB
      remoteRef:
        key: /lab/compute/postgres_db
    - secretKey: INTERNAL_API_KEY
      remoteRef:
        key: /lab/compute/internal_api_key
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-cluster-store
  target:
    name: postgres-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres.bvault-prod.svc.cluster.local:5432/{{ .POSTGRES_DB }}"
        INTERNAL_API_KEY: "{{ .INTERNAL_API_KEY }}"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-secret
  namespace: bvault-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "24h"
  target:
    name: ecr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .proxy_endpoint | replace "https://" "" }}": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: "ecr-gen-repo"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: bvault-prod
imagePullSecrets:
  - name: ecr-secret
