apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets-cluster-store
  annotations:
    external-secrets.io/ignore-maintenance-checks: "true"
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr-gen-repo
  namespace: bvault-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  region: us-east-1
