apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: gateway-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: gateway-f8e76ae78f52e09e6495853ae34fdc74d31f5147
