apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: gateway-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: gateway-318a50565e4b098e39dc6d88814ad6914950fbe2
