apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets-cluster-store
  annotations:
    external-secrets.io/ignore-maintenance-checks: "true"
spec:
  provider:
    aws:
      service: ParameterStore
      role: arn:aws:iam::854469103070:role/lab-k8s-workload
      region: us-east-1