apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-worker
  namespace: bvault-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-worker
  template:
    metadata:
      labels:
        app: analysis-worker
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: analysis-worker
          image: analysis-worker-image
          envFrom:
            - configMapRef:
                name: analysis-worker-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: music-store
              mountPath: /mnt/music-store
      volumes:
        - name: music-store
          persistentVolumeClaim:
            claimName: music-store-pvc
