apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: bvault-project
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.12.0
      helm:
        releaseName: longhorn
        valuesObject:
          preUpgradeChecker:
            # Disable the Helm pre-upgrade hook when Longhorn is managed by ArgoCD
            jobEnabled: false
          defaultSettings:
            defaultReplicaCount: 3
            backupTarget: "s3://longhorn-backups@us-east-1/"
            backupTargetCredentialSecret: longhorn-backup-secret
            storageMinimalAvailablePercentage: 15
            upgradeChecker: false
            guaranteedInstanceManagerCPU: 12
            autoDeletePodWhenVolumeDetachedUnexpectedly: true
            replicaAutoBalance: best-effort
            snapshotDataIntegrity: fast-check
            snapshotDataIntegrityCronjob: "0 4 * * *"
          persistence:
            defaultClass: true
            defaultFsType: ext4
            defaultClassReplicaCount: 3
            reclaimPolicy: Delete
            # Node selector for Longhorn Manager nodes
          longhornManager:
            nodeSelector:
              storage-node: "true"
            tolerations:
              - key: "storage"
                operator: "Equal"
                value: "longhorn"
                effect: "NoSchedule"
          longhornDriver:
            nodeSelector:
              storage-node: "true"
            tolerations:
              - key: "storage"
                operator: "Equal"
                value: "longhorn"
                effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
