apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  addresses:
  - 192.168.0.200-192.168.0.210
