apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-builder
  namespace: bvault-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: export-builder
  template:
    metadata:
      labels:
        app: export-builder
    spec:
      containers:
      - name: export-builder
        image: export-builder-image
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - configMapRef:
            name: export-builder-config
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: music-store
          mountPath: /mnt/music-store
      volumes:
      - name: music-store
        persistentVolumeClaim:
          claimName: music-store-pvc
