apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: export-builder-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: export-builder-5bd1a2246737d8cbe434eb49884ae637f5a173a5
