apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: export-builder-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: export-builder-beee73f1e3ec15e93c9e36b880ef489a375ae96f
