apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-store-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hdd
  hostPath:
    path: /mnt/music-store
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-store-pvc
  namespace: bvault-prod
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: local-hdd
  resources:
    requests:
      storage: 1.8Ti
