apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-dlp-ingest
  namespace: bvault-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-dlp-ingest
  template:
    metadata:
      labels:
        app: yt-dlp-ingest
    spec:
      containers:
        - name: yt-dlp-ingest
          image: yt-dlp-ingest-image
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: yt-dlp-ingest-config
            - secretRef:
                name: postgres-secret
