apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: yt-dlp-ingest-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: yt-dlp-ingest-a2b53f4b1323f58daaea87fc56c4480f7bfd19fa
