apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - configmap.yaml
  - service.yaml

images:
  - name: yt-dlp-ingest-image
    newName: 854469103070.dkr.ecr.us-east-1.amazonaws.com/bvault_app
    newTag: yt-dlp-ingest-3710507728b2a542077b7b8fb2294ea4e8fd4a27
