apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bvault-prod
type: Opaque
stringData:
  POSTGRES_DB: bvault
  POSTGRES_USER: bvault
  POSTGRES_PASSWORD: bvaultpassword
  DATABASE_URL: postgres://bvault:bvaultpassword@postgres.bvault-prod.svc.cluster.local:5432/bvault
